### ISSUE TITLE
Не удается создать контейнер - mysql-container

### ISSUE THREAD

**Issue by OlegDasheev** [OlegDasheev/qa-diploma#1]
**Шаги воспроизведения**
1. Запускаем IntelliJ IDEA;
2. Создаем проект используя данные с репозитория qa-diploma;
3. Запускаем Docker через docker-compose и dockerfile используя команду docker-compose up -d --build (необходим установленный на компьютере Docker Toolbox);

**Ожидаемый результат**
Создание mysql-контейнера ... сделано

**Фактический результат**
Создание mysql-контейнера ... ошибка

**Скриншот ошибки**
![aq-diploma 1](https://user-images.githubusercontent.com/79267970/123255501-81e7f980-d522-11eb-8b19-c8249f053c25.jpg)

**Log**
[log.txt](https://github.com/OlegDasheev/qa-diploma/files/6708797/log.txt)

**Окружение**
IntelliJ IDEA 2020.3.3 (Community Edition)
Runtime version: "11.0.10"
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 7, 64-разрядная система
Non-Bundled Plugins: Docker, Lombook Plugin, SeleniumPlugin, org.jetbrains.kotlin

**Comment by Vladanna** [comment]
Добрый день!

Чуть ниже в терминале написано что данный порт по которому вы хотите поднять mysql контейнер уже занят, необходимо убить все контейнеры которые у вас подняты
